cc_binary(
    name = "udpsink_to_logstash",
    srcs = [
        "udpsink_to_logstash.cpp",
    ],
    copts = [
#        "-DHAVE_NLOHMANN_JSON"
#        "-std=c++14"
    ],
    deps = [
        "//cpplog:cpplog",
#        "@fmtlib//:fmt",
#        "@nlohmann_json//:json"
    ]
)

