
cc_library(
    name = "cpplog",
    hdrs = [
        "sinks/console_sink.h",
        "sinks/glog_sink.h",
        "hex.h",
        "logging.h",
        "sink.h",
    ],
    srcs = [
        "config.h",
        "attachment.h",
        "record.h",
        "logging-inl.h",
        "sinks/console_sink_unix.h",
        "sinks/console_sink_windows.h",
    ],
    include_prefix = "cpplog",
    visibility = [
        "//visibility:public"
    ]
)

