
cc_library(
    name = "cpplog",
    hdrs = [
        "console_sink.h",
        "glog_sink.h",
        "hex.h",
        "json_builder.h",
        "logging.h",
        "sink.h",
        "support_nlohmann_json.h"
    ],
    srcs = [
        "config.h",
        "console_sink_unix.h",
        "console_sink_windows.h",
        "json_builder_inl.h",
        "logging-inl.h",
    ],
    include_prefix = "cpplog",
    visibility = [
        "//visibility:public"
    ]
)

